### login
POST localhost:8080/api/v1/auth/login
Content-Type: application/json

{
  "email": "aqua@gmail.com",
  "password": "123412341"
}

### Registration
POST localhost:8080/api/v1/auth/registration
Content-Type:  application/json

{ "name": "Temur",
  "surname": "chort",
  "email": "uytvbox2008@gmail.com",
  "password": "12345678"
}

### REGISTRAION
POST http://localhost:8080/api/v1/auth/registration
Content-Type: application/json

{
  "name": "Ali",
  "email": "myshukurov@gmail.com",
  "password": "12345678",
  "role": "ROLE_ADMIN",
  "status": "REGISTRATION",
  "photoId": "1"
}


###  LOGIN
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
  "email": "myshukurov@gmail.com",
  "password": "12345678"
}