### Create profile
POST http://localhost:8080/api/v1/profile/admin/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2OTIwMTYzODcsImVtYWlsIjoibnVyYmVrYW1pbm92MTNAZ21haWwuY29tIiwiZXhwIjoxNjkyMDE5OTg3LCJpc3MiOiJZT1UgVFVCRSBQT1JUQUwifQ.Pe8QIlYl-yeUtk3g-TPonUTU7UoukSGqqT7d9Sj768on_L4II3-DaO-ESn2_xcT9483Z_kbuSfyaEpAzFcdddw

{
  "name": "Vlai",
  "surname": "Valiyev",
  "email": "Vali123@gmail.com",
  "password": "12345678"
}

###Get detail
GET http://localhost:8080/api/v1/profile/user/get/detail
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2OTIyMTcyMzAsImVtYWlsIjoibnVyYmVrYW1pbm92MTNAZ21haWwuY29tIiwiZXhwIjoxNjkyMjI4MDMwLCJpc3MiOiJZT1UgVFVCRSBQT1JUQUwifQ.BRvGyldncTe7WRcXNH6BnTtUh5kkXpfQuDi6i976DWc3gYc8gMDanfFvdDa0m_VtCb5DqK9cuTtYaPIkNET2PQ

###Update password
PUT http://localhost:8080/api/v1/profile/user/update/password?newPassword=12345678910
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2OTIyMTcyMzAsImVtYWlsIjoibnVyYmVrYW1pbm92MTNAZ21haWwuY29tIiwiZXhwIjoxNjkyMjI4MDMwLCJpc3MiOiJZT1UgVFVCRSBQT1JUQUwifQ.BRvGyldncTe7WRcXNH6BnTtUh5kkXpfQuDi6i976DWc3gYc8gMDanfFvdDa0m_VtCb5DqK9cuTtYaPIkNET2PQ

###Update email
PUT http://localhost:8080/api/v1/profile/user/update/email?email=aminovnurbek007@gmail.com
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2OTIyMTcyMzAsImVtYWlsIjoibnVyYmVrYW1pbm92MTNAZ21haWwuY29tIiwiZXhwIjoxNjkyMjI4MDMwLCJpc3MiOiJZT1UgVFVCRSBQT1JUQUwifQ.BRvGyldncTe7WRcXNH6BnTtUh5kkXpfQuDi6i976DWc3gYc8gMDanfFvdDa0m_VtCb5DqK9cuTtYaPIkNET2PQ