### Create profile
POST http://localhost:8080/api/v1/profile/admin/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2OTIwMTYzODcsImVtYWlsIjoibnVyYmVrYW1pbm92MTNAZ21haWwuY29tIiwiZXhwIjoxNjkyMDE5OTg3LCJpc3MiOiJZT1UgVFVCRSBQT1JUQUwifQ.Pe8QIlYl-yeUtk3g-TPonUTU7UoukSGqqT7d9Sj768on_L4II3-DaO-ESn2_xcT9483Z_kbuSfyaEpAzFcdddw

{
  "name": "Vlai",
  "surname": "Valiyev",
  "email": "Vali123@gmail.com",
  "password": "12345678"
}

###Get detail
GET http://localhost:8080/api/v1/profile/user/get/detail
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2OTIwMjIyMjcsImVtYWlsIjoiVmFsaTEyM0BnbWFpbC5jb20iLCJleHAiOjE2OTIwMzMwMjcsImlzcyI6IllPVSBUVUJFIFBPUlRBTCJ9.WKJyEAB6AAE3xJet3uiprlu41iwQPdy-BBALAtQroK_YevqCf3z3_vxtY8-SZlZ512SGRtka8eW74XLs6tphkg

###Update password
PUT http://localhost:8080/api/v1/profile/user/update/password?newPassword=123456789
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2OTIwMjIyMjcsImVtYWlsIjoiVmFsaTEyM0BnbWFpbC5jb20iLCJleHAiOjE2OTIwMzMwMjcsImlzcyI6IllPVSBUVUJFIFBPUlRBTCJ9.WKJyEAB6AAE3xJet3uiprlu41iwQPdy-BBALAtQroK_YevqCf3z3_vxtY8-SZlZ512SGRtka8eW74XLs6tphkg

###Update email
PUT http://localhost:8080/api/v1/profile/user/update/email?email=Vali1234@gmail.com
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2OTIwMjIyMjcsImVtYWlsIjoiVmFsaTEyM0BnbWFpbC5jb20iLCJleHAiOjE2OTIwMzMwMjcsImlzcyI6IllPVSBUVUJFIFBPUlRBTCJ9.WKJyEAB6AAE3xJet3uiprlu41iwQPdy-BBALAtQroK_YevqCf3z3_vxtY8-SZlZ512SGRtka8eW74XLs6tphkg